spring:
  application:
    name: Food-Ordering-System
  datasource:
    url: jdbc:mysql://localhost:3306/food_ordering_system
    username: root
    password: Prasanna@5030
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: msprasannakumar19@gmail.com
    password: ppcv upce yyta gxnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: TRACE
    web: debug


