spring:
  application:
    name: Food-Ordering-System
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/food_ordering_system
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Prasanna@5030}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: msprasannakumar19@gmail.com
    password: ppcv upce yyta gxnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  mvc:
    cors:
      mappings:
        /api/**:
          allowed-origins: "http://localhost:4200, http://frontend:4200"  # Allow both localhost and the Docker service name
          allowed-methods: "GET, POST, PATCH, PUT, DELETE, OPTIONS"
          allowed-headers: "Content-Type, Authorization"
          exposed-headers: "Authorization"
          allow-credentials: true
          max-age: 3600

logging:
  level:
    org.springframework.security: TRACE
    web: debug




